// Central site configuration. Edit here — everything else reads from this.

export const site = {
  name: "Unexplo",
  // Used in <title> templates and structured data.
  legalName: "Unexplo",
  domain: "unexplo.com",
  url: "https://unexplo.com",
  tagline: "Governed, AI-native data discovery.",
  description:
    "Unexplo is a governed, AI-native data discovery tool. Its core engine is built on dbt, Kedro, and Obsidian — modular enough to adapt to any requirement, with built-in compatibility and handoff so it fits any business analytics system.",
  email: "contact@unexplo.com",
  // Default Open Graph image (1200x630). Generated by scripts/generate-og.mjs.
  ogImage: "/og.png",
  locale: "en_US",
} as const;

export const socials = [
  {
    label: "X",
    handle: "@unexplo2k",
    url: "https://x.com/unexplo2k",
    icon: "x",
  },
] as const;

// Primary navigation — single-page landing, so these are in-page anchors.
// The header picks these up automatically.
export const nav = [
  { label: "Engine", href: "/#engine" },
  { label: "Principles", href: "/#principles" },
  { label: "Handoff", href: "/#handoff" },
] as const;

// The three tools that make up the core discovery engine.
export const engine = [
  {
    name: "dbt",
    role: "Transformation & lineage",
    description:
      "Modular, version-controlled transformations give every metric a traceable, governed lineage — no black boxes.",
  },
  {
    name: "Kedro",
    role: "Pipelines & orchestration",
    description:
      "Reproducible, structured pipelines turn exploratory work into production-grade data flows you can trust.",
  },
  {
    name: "Obsidian",
    role: "Knowledge & discovery",
    description:
      "A linked knowledge graph keeps context, decisions, and discovery connected to the data itself.",
  },
] as const;

// UNEXPLO, spelled out — the principles of the engine, one per letter.
export const acronym = [
  { letter: "U", word: "Unified", note: "One discovery surface across your whole stack." },
  { letter: "N", word: "Native", note: "AI-native from the core engine outward." },
  { letter: "E", word: "Exploration", note: "Rapid prototyping over rigid, dumb process." },
  { letter: "X", word: "eXtensible", note: "Adapts to any business analytics system." },
  { letter: "P", word: "Prototyping", note: "Requirements that make sense to engineers." },
  { letter: "L", word: "Lineage", note: "Governed, traceable, and auditable by default." },
  { letter: "O", word: "Orchestration", note: "Seamless handoff into production." },
] as const;
